### ISSUE TITLE
I have the Family Edition AND Couples edition packs

### ISSUE THREAD

**Issue by pauljones0** [jonathan-lph/wnrs#3]
How should I add them? Just submit a js file with the questions typed up, following similar formats?

**Comment by pauljones0** [comment]
I just did the family deck, but don't know if:
- The formatting is correct
- If some things should be changed or left out
- Main deck folder or expansion?

C:\Users\bethe\Downloads\work\family.json

**Comment by jonathan-lph** [comment]
Thanks for the support! The family edition is now live. 
A future reference for the keys in the JSON files if you will be so kind to include Couples Edition as well. :)

- `edition`: Small text appears on-card under WNRS trademark.
- `theme`: Color theme detailed under `$card-themes` in `styles/theme.scss`. For most cases it will be `"main"`.
- `preview`: Text contained in the small letter/paper inside the expansion packs.
- `instruction`: Game-specific instructions, warnings, or additional information.

**Comment by pauljones0** [comment]
I'll try to get the couple's edition done in the next few days.

For the family.json, the preview is word-for-word correct, but the instructions are paraphrased for brevity. I hope this is okay.

**Comment by pauljones0** [comment]
Couples.json added.
